version: '3.8'

services:
  node_chat_server:
    build:
      context: ..
      dockerfile: ./docker/node.Dockerfile
    container_name: node_chat_server
    volumes:
      - /var/www/node_chat_server

  node_chat_nginx:
    build:
      context: ..
      dockerfile: ./docker/nginx.Dockerfile
    container_name: node_chat_nginx
    ports:
      - 80:80
    depends_on:
      - node_chat_server
